/*
 * DO NOT EDIT.
 *
 * Generated by the protocol buffer compiler.
 * Source: MessageCollection.proto
 *
 */

import Foundation
import SwiftProtobuf


struct MessageCollection: SwiftProtobuf.Message, SwiftProtobuf.Proto3Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf.ProtoNameProviding {
  public var swiftClassName: String {return "MessageCollection"}
  public var protoMessageName: String {return "MessageCollection"}
  public var protoPackageName: String {return ""}
  public static let _protobuf_fieldNames: FieldNameMap = [
    1: .same(proto: "items", swift: "items"),
  ]


  var items: [Message] = []

  init() {}

  public mutating func _protoc_generated_decodeField<T: SwiftProtobuf.FieldDecoder>(setter: inout T, protoFieldNumber: Int) throws {
    switch protoFieldNumber {
    case 1: try setter.decodeRepeatedMessageField(fieldType: Message.self, value: &items)
    default: break
    }
  }

  public func _protoc_generated_traverse(visitor: SwiftProtobuf.Visitor) throws {
    if !items.isEmpty {
      try visitor.visitRepeatedMessageField(value: items, fieldNumber: 1)
    }
  }

  public func _protoc_generated_isEqualTo(other: MessageCollection) -> Bool {
    if items != other.items {return false}
    return true
  }
}
