/*
 * DO NOT EDIT.
 *
 * Generated by the protocol buffer compiler.
 * Source: MessageCollection.proto
 *
 */

import Foundation
import SwiftProtobuf


public struct MessageCollection: ProtobufGeneratedMessage {
  public var swiftClassName: String {return "MessageCollection"}
  public var protoMessageName: String {return "MessageCollection"}
  public var protoPackageName: String {return ""}
  public var jsonFieldNames: [String: Int] {return [
    "items": 1,
  ]}
  public var protoFieldNames: [String: Int] {return [
    "items": 1,
  ]}

  public var items: [Message] = []

  public init() {}

  public init(items: [Message] = [])
  {
    if !items.isEmpty {
      self.items = items
    }
  }

  public mutating func _protoc_generated_decodeField(setter: inout ProtobufFieldDecoder, protoFieldNumber: Int) throws -> Bool {
    let handled: Bool
    switch protoFieldNumber {
    case 1: handled = try setter.decodeRepeatedMessageField(fieldType: Message.self, value: &items)
    default:
      handled = false
    }
    return handled
  }

  public func _protoc_generated_traverse(visitor: inout ProtobufVisitor) throws {
    if !items.isEmpty {
      try visitor.visitRepeatedMessageField(value: items, protoFieldNumber: 1, protoFieldName: "items", jsonFieldName: "items", swiftFieldName: "items")
    }
  }

  public func _protoc_generated_isEqualTo(other: MessageCollection) -> Bool {
    if items != other.items {return false}
    return true
  }
}
